edited irace parameter file

diff --git a/tuning/target-runner b/tuning/target-runner
--- a/tuning/target-runner
+++ b/tuning/target-runner
@@ -15,66 +15,52 @@
 # RETURN VALUE:
 # This script should print one numerical value: the cost that must be minimized.
 # Exit with 0 if no error, with 1 in case of error
-###############################################################################
-error() {
-    echo "`TZ=UTC date`: $0: error: $@"
-    exit 1
-}
+###########main####################################################################
+EXE=../main.py
 
-# This parses the arguments given by irace. Do not touch it!
+
 CONFIG_ID=$1
 INSTANCE_ID=$2
 SEED=$3
 INSTANCE=$4
-shift 4 || error "Not enough parameters"
+
+shift 4 || exit 1
 CONFIG_PARAMS=$*
-# End of parsing
 
-## Find our own location.
-# BINDIR=$(dirname "$(readlink -f "$(type -P $0 || echo $0)")")
+LOGS=c${CONFIG_ID}-${INSTANCE_ID}.log
+DAT_FILE=c${CONFIG_ID}-${INSTANCE_ID}.dat
+touch ${DAT_FILE}
 
-# EDIT THIS: Path to your executable
-EXE=~/bin/program 
-# EDIT THIS: Specify how parameters are given to your executable
-EXE_PARAMS="--time 5 -i $INSTANCE --seed ${SEED} ${CONFIG_PARAMS}"
-
-if [ ! -x "$(command -v ${EXE})" ]; then
-    error "${EXE}: not found or not executable (pwd: $(pwd))"
-fi
-
-# # If the program just prints a number, we can use 'exec' to avoid creating
-# # another process, but there can be no other commands after exec, only exit.
-# exec $EXE ${EXE_PARAMS}
+# If the program just prints a number, we can use 'exec' to avoid
+# creating another process, but there can be no other commands after exec.
+#exec $EXE ${FIXED_PARAMS} -i $INSTANCE ${CONFIG_PARAMS}
 # exit 1
+# 
+# Otherwise, save the output to a file, and parse the result from it.
+# (If you wish to ignore segmentation faults you can use '{}' around
+# the command.)
+#python -m scoop $EXE -v ${CONFIG_PARAMS} --datfile ${DAT_FILE} > ${LOGS} 2>&1
+#echo $EXE $*
+#python $EXE -v ${CONFIG_PARAMS}
+python3 $EXE -v ${CONFIG_PARAMS} --datfile ${DAT_FILE} > ${LOGS} 2>&1
 
-# These files are saved in execDir. Saving them in /tmp may be faster. 
-STDOUT=c${CONFIG_ID}-${INSTANCE_ID}-${SEED}.stdout
-STDERR=c${CONFIG_ID}-${INSTANCE_ID}-${SEED}.stderr
+error() {
+    echo "`TZ=UTC date`: error: $@"
+    exit 1
+}
 
-# # Otherwise, save the output to a file, and parse the result from it.  (If
-# # you wish to ignore segmentation faults you can use '{}' around the
-# # command.)
-# # If the command below fails, but you are not sure why, it may be useful to
-# # print it before executing using 'echo', as in:
-# echo "$EXE ${EXE_PARAMS} 1> ${STDOUT} 2> ${STDERR}"
-$EXE ${EXE_PARAMS} 1> ${STDOUT} 2> ${STDERR}
-
-# # This may be used to introduce a delay if there are filesystem issues.
-# SLEEPTIME=1
-# while [ ! -s "${STDOUT}" ]; do
-#     sleep $SLEEPTIME
-#     let "SLEEPTIME += 1"
-# done
-
-if [ ! -s "${STDOUT}" ]; then
-    error "${STDOUT}: No such file or directory"
+# This is an example of reading a number from the output.
+# It assumes that the objective value is the first number in
+# the first column of the last line of the output.
+if [ -s "${DAT_FILE}" ]; then
+	COST=$(cat "${DAT_FILE}" | grep -e '^[0-9]' | cut -f1)
+	# use echo "-$COST" to
+	# Negative because score is maximised but irace minimises.
+    echo "$COST"
+    rm -f "${LOGS}" "${DAT_FILE}" 
+    exit 0
+else
+    error "${DAT_FILE}: No such file or directory"
 fi
-# This is an example of reading a number from the output.  It assumes that the
-# objective value is the first number in the first column of the last line of
-# the output.
-COST=$(tail -n 1 ${STDOUT} | grep -e '^[[:space:]]*[+-]\?[0-9]' | cut -f1)
-echo "$COST"
-# Comment the following line if you wish to preserve temporary files
-rm -f "${STDOUT}" "${STDERR}"
-exit 0
+
 
